name: update page

on:
  workflow_dispatch:
  push:
    branches:
      - master # restrict to master branch in order to avoid infinite loop
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0
      - name: clone kernel
        uses: actions/checkout@v4
        with:
          repository: torvalds/linux
          path: linux
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - run: pip install GitPython requests tqdm
      - run: python3 ./linux-statistic.py --path ./linux
      - run: tar cf pages.tar index.html result.json detail/
      - uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: pages.tar

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
