name: update page

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"
          cache: "pip"
      - run: pip install GitPython requests tqdm
      - run: python3 ./linux-statistic.py
      - name: Commit changes to gh-pages and push
        run: |
          git checkout gh-pages
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add index.html result.json detail/
          git commit -m "ci: update page"
          git push

      

